- src/bin/cog.rs
- src/lib.rs
Noticed typo while fixing #34; fixed it here.
> fix: typo in get_committer

- src/bin/cog.rs
- src/lib.rs
- src/version.rs
- tests/cog_bump_test.rs
Implementation of the feature discussed in #21 
Closes #21
> feat(cli): bump --pre flag to set the pre-release version

- README.md
- src/version.rs
Adds check to prevent auto bumping major when we're on a `0.y.z` version (initial development).
Closes #58
> Fix incorrect behavior of 0.y.z autobumps

- src/bin/cog.rs
- src/lib.rs
- src/settings.rs
This PR adds the `--config` flag to `cog bump` closing #74.  
I couldn't figure any better way to pass the custom config file path to the `Settings` struct apart from passing it in the `Settings::get` function. 
But this change results in having to pass `None` whenever a custom config path is not needed. 
For example: `Settings::get(&repo, None).unwrap_or_default().authors` in `lib.rs:69`
Please let me know if this approach is acceptable, or if there could be a better approach to passing the custom `config_path` parameter to the `Settings` struct.
Also, I've tested this flag manually on sample git repos, and the hooks specified by the config file path run correctly.  Would we need to add any unit tests to test this flag?
Thanks.
> feat(bump): add --config flag to cog bump

- src/git/repository.rs
- tests/cog_bump_test.rs
This pull request is a potential fix for #83. It uses `semver::Version` to turn the tags into version objects that can be sorted based on semver convention.
There is also a test included that fails on the master version and succeeds with this fix.
Please bare in mind that Rust is not my daily language and the current state of the PR should be considered a starting point rather than the fix.
I allowed edits by maintainers for this PR, please use it!
> Sort tags on semver format to discoved latest tag

- src/bin/coco.rs
- src/bin/cog.rs
- src/conventional/changelog.rs
- src/conventional/commit.rs
- src/conventional/version.rs
- src/git/repository.rs
- src/hook/mod.rs
- src/hook/parser.rs
- src/lib.rs
- src/log/filter.rs
- src/log/output.rs
- tests/coco_commit_test.rs
Highlights:
- Use `Deref` / `IntoIterator` when applicable
- Avoid some minor redundant allocation
> Clean up minor code details

- src/bin/coco.rs
Hello!
While generating shell completions for `coco`, I realized it first tries to open the repository in the current directory thus fails to generate completions when the current directory is not a git repository:
```
Error: could not find repository from '/build/cocogitto/src/cocogitto-3.0.0'; class=Repository (6); code=NotFound (-3)
```
These are two separate actions so I think it does not need to open the repository before generating shell completions.
This PR fixes this issue by moving the `CocoGitto::get()` call to the scope where it is needed.
> fix: generate completions without opening a repository

- Cargo.lock
- Cargo.toml
- src/bin/coco.rs
- src/bin/cog.rs
Replaces raw clap with structopt in `cog` to avoid boilerplate code (manual checks and clap method calls).
I also attempted to do the same in `coco` but structopt doesn't like the combination of required positional args and subcommands.
> Switch cog arg parsing to structopt

- Cargo.lock
- Cargo.toml
- src/bin/coco.rs
Implements #103
Default look:
With the `-B` flag:
> Add edit flag for coco

- cog.toml
- src/git/revspec.rs
Annotated tags are unique git objects with their own hashes.
Consequently, prior to this commit, cog check would not recognize these
tags in the commit ranges it checked.
This commit fixes this bug by detecting if a tag is an annotated tag,
and identifying its associated commit.
Fixes #151.
> fix: support annotated tags in cog check -l

- Cargo.toml
- src/bin/coco.rs
- src/bin/cog.rs
- src/bin/cog_commit.rs
- tests/cog_tests/commit.rs
- tests/cog_tests/mod.rs
Closes #157 
The common `coco` utils have been moved to a separate `cog_commit` module, to avoid code duplication.
Adds a deprecation warning to `coco`'s help as well as prints it to stderr before starting its logic.
Should be a backwards-compatible feature, with the option to remove `coco` at a breaking change bump.
> Duplicate 'coco' as 'cog commit'

- cog.toml
- src/git/commit.rs
Implemented the fix for #145, and added a test that catches the bug, and now passes
> fix: correctly identify empty repository when commiting

- src/git/commit.rs
- src/git/diff.rs
- src/git/repository.rs
- src/git/revspec.rs
- src/git/tag.rs
As discussed in #177, the combination of two issues causes many tests to pass, even when errors occur.
Here I added all the missing ";" in the tests. 
While this might fix the test logic, the real problem is that returning an `Err` from the tests does not fail them.
Not sure if this is enough to merge, or should we wait until the tests are entirely fixed? Up to you, @oknozor.
> Fix broken tests

- src/conventional/commit.rs
- src/hook/mod.rs
- src/lib.rs
This should fix the issue where cog edit does not pick the type errors. 
A test is needed to ensure there is no cog check regression
Also cog edit should be tested manually since it relies on the user $EDITOR
> fix: build commit type error regardless of the command used

- README.md
Just tried `cargo install cocogitto` and it failed because it tried to use deps that were too new 😄
> docs: suggest running a locked install when using cargo

- .github/workflows/Release.yml
- cog.toml
`cargo-bump` seems stale since 2019, switching to a newer crate would set a good example for users
> chore: use cargo-edit for bumping crate version

- Cargo.lock
- Cargo.toml
- src/settings/mod.rs
When doing `cargo install cocogitto` `cargo` doesn't respect the `Cargo.lock` but it will update as far as it can based on the semantic version.
So for me it pulled in `0.12.0` which failed to compile.
I _COULD_ lock down `config` inside of `Cargo.toml` with `=0.12.0` but I believe it's better not to, to use it as a forcing mechanism to update those `0.*` packages ASAP.
> fix: updated config to 0.12.0 (latest as of now) + usage

- src/conventional/changelog/error.rs
- src/conventional/error.rs
- src/git/error.rs
- src/hook/mod.rs
- src/lib.rs
Should allow us to piggyback on Rust 1.56+ a little bit longer 😄
> fix: avoid using the format ident capturing Rust feature

- Cargo.lock
- Cargo.toml
- src/bin/cog.rs
- src/conventional/changelog/release.rs
- src/conventional/commit.rs
- src/conventional/version.rs
- src/lib.rs
- tests/cog_tests/bump.rs
- tests/cog_tests/check.rs
- tests/cog_tests/init.rs
- tests/cog_tests/verify.rs
- tests/helpers.rs
- tests/lib_tests/bump.rs
- tests/lib_tests/init.rs
Add a `dry-run` option for bump command.  
On a `cog bump -a -d`, the target version will be returned.  
In order to get only the version on stdout, other text outputs are diverted to stderr, using stderrlog. The default log level is INFO (no logs positionned to debug), meaning that all the outputs are still displayed by default, without any extra info (log level, timestamp, etc…) to preserve the current behaviour.  
The v flag has been reaffected to log leverl (-v for ERROR, -vv for WARNING, -vvv for INFO, …), but I don’t know if it’s needed / relevant.
> Add dry-run option for bump command

- src/conventional/changelog/release.rs
- src/git/revspec.rs
- tests/cog_tests/changelog.rs
In addition to fixing the endless recursion for this type of revspec tag revspec are now exclude the starting point. For instance '1.0.0..1.0.3' will collect all tags starting from >1.0.0. In the other hand, commit revspec starting point are inclusive.
#220 #227
> fix: fix stackover flow on 'oid..' resvpec

- Cargo.lock
- Cargo.toml
- src/bin/cog/commit.rs
- src/bin/cog/main.rs
Normally I would wait a bit more with a new clap release, but this one drops some dependencies (`indexmap`, `textwrap`).
Notable changes: clap has dropped help output coloring for now.
> chore: bump clap version to 4.0

- src/bin/cog/main.rs
- src/settings/mod.rs
Without the ability to specify the `from_latest_tag` in the settings file it is very difficult to add cocogitto to an existing repository as you need to do one of the following:
* remember to only run `cog install-hook commit-msg` otherwise your pushes can fail depending on the local and remote states
* or manually edit the hooks, defeating the nice ux of the `cog install-hook` command
> feat: add from_latest_tag to settings

- src/lib.rs
Fixes chore commits from bumping not being signed.
> fix: signing for bump chore commits

- src/bin/cog/main.rs
Hello! 🐻
From `cog(1)`:
```
SUBCOMMANDS
Cog-help(1)
Print this message or the help of the given subcommand(s)
```
However, it is not possible to generate a manpage for `cog-help` since it's a built-in command:
```sh
$ cog generate-manpage help
thread 'main' panicked at 'Requested non-existent subcommand', src/bin/cog/main.rs:487:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This PR disables the help subcommand for `cog(1)` thus strips the `cog-help` section from manpage.
> fix: disable help subcommand for `cog(1)`

- src/bin/cog/main.rs
- src/command/bump/monorepo.rs
- src/command/bump/package.rs
- src/command/bump/standard.rs
- src/git/tag.rs
- tests/helpers.rs
- tests/lib_tests/bump.rs
Many projects use annotated commits for their releases. This commit extends `cog bump` with the `-A MSG`/`--annoted MSG` argument, which will create an annotated tag with the tag message `MSG`.
Much like the bump hooks, `{{version}}` and `{{latest}}` can be used in the provided tag message and will be replaced accordingly.
> feat(bump): support annotated tags

- Cargo.lock
- Cargo.toml
- src/bin/cog/main.rs
- src/conventional/changelog/template.rs
- tests/assets/commit_message.txt
- tests/cog_tests/verify.rs
"cog verify" can now read the commit message from a file with the "-f" or "--file" parameter. This parameter is mutually exclusive with the "message" argument.
implement #279
> feat(cli): add file parameter to verify command

- src/bin/cog/main.rs
- src/command/check.rs
- tests/cog_tests/check.rs
- tests/lib_tests/cocogitto.rs
Closes #284.
The changes included in this PR allows accepting the commit range as an optional CLI argument. However, `clap` would raise an error if both `--from-latest-tag` and commit range are specified. This PR also includes some unit tests, let me know if any more tests are needed.
A problem that I see with the current implementation is that parsing a commit range from a string panics if the string is of an invalid format (check the `From<&str>` implementation of `RevspecPattern`). This would be a bad experience for the users. We should consider implementing `FromStr` or `TryFrom` instead, and raise an error instead of panicking. Depending on what's preferable, I can take this up on a separate PR.
> feat(check): allow running check on commit range

- src/bin/cog/main.rs
Groups are better suited for this task, and arguably make for more readable code.
Also fills in missing flag docs.
> refactor(cli): adjust cog-verify args

- Cargo.toml
- docs/Packaging.md
- src/bin/cog/main.rs
- src/bin/cog/mangen.rs
I've taken a look at my original `cog generate-manpages` design and it seems unwieldy in hindsight. It requires unnecessary effort from a packager to manually discover subcommands and request them one by one. Also the generated manpages for subcommands are not correct since the perceived name is `foo-subcommand` instead of `cog-foo-subcommand`.
This switches to simply giving the command the directory for the output and then automatically creating all manpages ourselves.
One tidbit is having to enable the `string` clap feature in order to adjust the command names manually. This shouldn't be a big problem but I wanted to point out that it's there.
As an aside, I didn't mark this change as breaking since I don't think generating manpages should be considered a part of the main public API. …
> Manpages v2

- src/bin/cog/main.rs
This makes the manpages and help outputs a little more cohesive.
> style: rename 'Cog' to 'cog' internally

- cog.toml
- src/bin/cog/main.rs
- src/command/changelog.rs
- src/command/check.rs
- src/conventional/bump.rs
- src/git/error.rs
- src/git/monorepo.rs
- src/git/revspec.rs
This PR updates the parsing logic for `RevspecPattern` to raise an error instead of panicking, by replacing the `From<&str>` implementation with `FromStr`, as discussed in https://github.com/cocogitto/cocogitto/pull/286#issue-1718201238.
Let me know if using a separate error enum/struct would be preferable instead of adding an enum variant to `Git2Error`, and if a `TryFrom` implementation would also be required.
> refactor(revspec): raise error instead of panicking when parsing `RevspecPattern`

- src/git/revspec.rs
Rather than implementing a tag walk ourselves, leverage `git describe`.
Tested: Ran `cargo nextest run` to ensure all local tests passed.
Summary [   0.496s] 226 tests run: 226 passed, 0 skipped
> refactor(revspec): use git describe for finding latest tag

- src/conventional/commit.rs
- src/conventional/error.rs
- src/settings/error.rs
- src/settings/mod.rs
PR makes minor changes to internal implementation details in support of deprecating the [Cocogitto GitHub Bot](https://github.com/cocogitto/cocogitto-bot/pull/13)'s use of `conventional_commit_parser` in favor of using Cocogitto itself to validate commit messages.
> feat: gha bot support

- Cargo.lock
- Cargo.toml
When doing `cargo install --locked`, pest and hermit-abi pop up as yanked.
> chore: bump yanked crates

- src/bin/cog/main.rs
- src/command/git_hooks.rs
- src/git/hook.rs
This PR adds a command line option to overwrite existing git-hooks for the `install-hook` command, as requested in #299.
> feat: add option to overwrite existing git-hooks

- src/hook/mod.rs
- src/hook/parser.rs
- src/hook/version_dsl.pest
Adds the ability to do `{{version.major}}` `{{version.minor}}` or `{{version.patch}}` in hook.
Here's an example on how I use it: https://github.com/ecsact-dev/ecsact_parse/blob/main/cog.toml
I didn't add tests, but I'm happy to if this is an acceptable change. Let me know!
> feat: version access substitution

- src/command/bump/mod.rs
- src/conventional/bump.rs
- src/conventional/changelog/release.rs
- src/conventional/changelog/serde.rs
- src/conventional/commit.rs
- src/log/filter.rs
- src/settings/mod.rs
> feat: allow bumping with other commit types

- docs/website/config/README.md
Remembered seeing this in the commits but couldn't find it in the docs :D
> docs(commits-types): bump minor and patch options

- docs/website/guide/README.md
- src/bin/cog/main.rs
- src/command/bump/mod.rs
- src/command/bump/monorepo.rs
- src/command/bump/package.rs
- src/command/bump/standard.rs
- tests/cog_tests/bump.rs
- Soft-Fork a project
- Make private releases with added functionality
- Create a private release while honoring upstream SemVer
- That's what `build` ~~is~~ can be used for
- Add `--build foo.bar.bui` to the `cog bump` command
> feat: add build version to command

- docs/website/config/README.md
- src/command/bump/monorepo.rs
- src/command/bump/package.rs
- src/command/bump/standard.rs
Fixes some issues in the documentation and also a typo emitted by the CLI.
* Fixes typo in code `skiped` -> `skipped`
* Uppercases all the beginnings letters of the `Description` field so it's consistent
* Add documentation to `Changelog` section similar to other top level objects
* Add documentation to `Mono-repository packages` section similar to other top level objects
* Add missing `package_template` property
* Add missing `from_latest_tag` property
* Fix other small typos in documentation
> chore: update docs

- Cargo.lock
- Cargo.toml
- cog.toml
- crates/cocogitto-config/Cargo.toml
- crates/cocogitto-config/src/changelog.rs
- crates/cocogitto-config/src/commit.rs
- crates/cocogitto-config/src/git_hook.rs
- crates/cocogitto-config/src/lib.rs
- crates/cocogitto-config/src/monorepo.rs
- crates/cocogitto-schema/Cargo.toml
- crates/cocogitto-schema/src/main.rs
- crates/cocogitto/src/command/init.rs
- docs/website/.vuepress/public/cog-schema.json
- justfile
Example of generating json docs from the `Settings` struct using the `JSONSchema` derive macro from [schemars](https://docs.rs/schemars/latest/schemars/). It just needs some entrypoint in the codebase where it can output the schema. This pull request uses a second `bin` called `schema` to do it. I don't know what's best practice. Another alternative would be to use `example` instead of `bin`.
This pull request tries to separate the schema building code by putting it under a separate feature flag `json_schema` so that the cog CLI isn't (potentially) affected.
How to generate:
```bash
cargo run --release --bin schema --features=json_schema > docs/website/.vuepress/public/cog-schema.json
```
What's missing:
- When to generate the json schema in the workflows
- Should json schema be …
> docs: add json schema generation

- README.md
- cog.toml
Just to make it a little easier to find some basic docs. Thanks for the great documentation!
> docs(config): add link to cog.toml config reference to README and cog.toml

- docs/website/index.md
This PR will update the documentation website's homepage to include MacOS install instructions, which are already present in the repository's README.
> docs(website): include MacOS install instructions on homepage

- README.md
Updates outdated link for `tera` dep
> docs: update tera link in README.md

- src/lib.rs
Added a method to the CocoGitto implementation to allow for using CocoGitto at custom paths, not only the current working directory.
I need it in [cococonscious/koji](https://github.com/cococonscious/koji) for the git-like "-C" argument and integration tests.
> feat: open repo at path

- website/index.md
Previously Getting Started pointed to `/guide.html`:
Which doesn't exist. The user guide is at `/guide/init.html`.
> fix: set correct url for Getting Started

- src/bin/cog/commit.rs
The order of commit type options in cog commit --help (and also in the manpage and shell completion) was random on each call. Use .sorted() to get a stable ordering and avoid confusion.
(I am not experienced with rust so if this is the wrong way please tell)
> fix(commit): fixed order of commit type options

- README.md
Noticed the typo while reading the README.md, this PR fixes it.
> docs: fix capitalisation of NixOS

- .github/workflows/CI.yml
- .github/workflows/Deploy.yaml
add `aarch64-apple-darwin` target for the CI run.
> chore(workflows): add `aarch64-apple-darwin` target

- src/conventional/commit.rs
- src/conventional/error.rs
- src/settings/mod.rs
- tests/cog_tests/check.rs
- tests/cog_tests/commit.rs
Personally, I'm missing this feature. I realise that, ideally, suggestions for scopes are desirable (as written in #42) but having this feature in cocogitto without suggestions is a great improvement already, especially for CI.
The tests fail for me with these changes but I can't figure out why. Some pointers would be appreciated here! Besides the failing tests this is done :)
> feat(check): Support commit scope checking

- src/git/commit.rs
- src/git/repository.rs
Resolve a signingkey of `~/.ssh/key.pub` to `/home/kristof/.ssh/key.pub` using `git2`.
Test written to validate behavior on Linux & Windows.
Note that there are other variables being read that I haven't updated, but could benefit from reading the variable as a `PathBuf` and not a `&str`.
Happy to take this up in a future PR.
> Resolve tilde in the signingkey to home
