- README.md
> docs: add AUR package to README

- src/bin/cog.rs
- src/conventional/changelog.rs
- src/error.rs
- src/git/repository.rs
- src/lib.rs
> feat(bump): stash hook generated changes on prehook failure

- src/conventional/changelog.rs
- src/conventional/commit.rs
- src/conventional/version.rs
- src/git/repository.rs
- src/hook.rs
- src/lib.rs
- tests/helper.rs
Some highlights:
- use anyhow macros where applicable
- use the write! macro to append formatted content to a String
- simplify Repository::get_latest_tag and avoid intermediate Vec collection
> Refactor code

- README.md
- src/bin/cog.rs
- src/conventional/commit.rs
- src/git/hook.rs
- src/hook/parser.rs
- src/lib.rs
- tests/git_test.rs
> feat: add check from latest tag option

- README.md
- src/bin/cog.rs
- src/conventional/commit.rs
- src/conventional/version.rs
- src/git/repository.rs
- src/hook/parser.rs
- src/lib.rs
- src/log/output.rs
- tests/cog_changelog_test.rs
- tests/cog_check_test.rs
- tests/helper.rs
This still needs some unit tests
> feat: generate markdown changelog for a given version

- src/hook/mod.rs
- src/hook/parser.rs
This address a bug where parsing hook expression produce an incorrect result.
```toml
post_bump_hooks = [
"coco chore 'bump snapshot to {{version+1minor-pre}}'",
]
```
Before the patch parsing the following hook would produce the following tokens : 
`"coco", "chore" "bump snapshot to" "0.0.1-pre ""`
This would produce an error when running cog bump due to the trailing quote.
Now this produce the following tokens : 
`"coco", "chore" "bump snapshot to 0.0.1-pre"`
> fix(hooks): use range to replace version expression in hooks

- src/git/repository.rs
Fixes problems with unspecified tag order in #94
> Sort tag names before searching

- cog.toml
> chore: add orhun to the contributors list

- src/conventional/commit.rs
Unlike other cocogitto commands, `cog verify` takes an input string and
does not rely on git internals to git rid of the comments. Consequently,
when used as a git hook, `verify` will fail for git commits that start
with a comment that appears to break conventional commit standards.
This commit strips away these comment lines within `verify`.
Fixes #153.
> fix: ignore comment lines in cog verify

- Cargo.lock
- Cargo.toml
- src/bin/coco.rs
- src/bin/cog.rs
> Switch arg parsing to clap v3

- README.md
Waiting for package to be merged
> add(packaging): nixos install onliner

- .github/workflows/CI.yml
- Cargo.lock
- Cargo.toml
- src/git/revspec.rs
- src/git/stash.rs
- src/git/tag.rs
- tests/cog_tests/bump.rs
- tests/cog_tests/init.rs
- tests/helpers.rs
Bump bump sealed_test crate to 0.2.0 to fix an issue where using "?" did 
not causes the test to fail as expected. After fixing this by bumping sealed_test
turns out a few tests were failing and had to be refactored.
closes #177
> test: fix sealed_test question mark unwrapping

- Cargo.lock
- src/conventional/changelog/error.rs
- src/conventional/changelog/mod.rs
- src/conventional/changelog/template.rs
- src/conventional/commit.rs
- src/conventional/error.rs
- src/conventional/mod.rs
- src/conventional/version.rs
- src/error.rs
- src/git/commit.rs
- src/git/error.rs
- src/git/hook.rs
- src/git/mod.rs
- src/git/repository.rs
- src/git/revspec.rs
- src/git/stash.rs
- src/git/status.rs
- src/git/tag.rs
- src/hook/error.rs
- src/hook/mod.rs
- src/hook/parser.rs
- src/lib.rs
- src/log/output.rs
- src/settings/error.rs
- src/settings/mod.rs
- tests/cog_tests/bump.rs
- tests/cog_tests/commit.rs
- tests/helpers.rs
- tests/lib_tests/bump.rs
This PR solve #137 by using custom errors in the private API.
> WIP - refactor: error handling 

- src/bin/cog.rs
- src/conventional/changelog/mod.rs
- src/conventional/changelog/release.rs
- src/conventional/changelog/renderer.rs
- src/conventional/changelog/template.rs
- src/lib.rs
- src/settings/mod.rs
- tests/cog_tests/changelog.rs
- tests/cog_tests/template.md
> fix(changelog): allow template context to be used in custom templates

- src/hook/mod.rs
This will allow to use environment variables in hooks without
calling a subshell explicitly.
> feat(hook): use a subshell by default on linux

- src/bin/cog.rs
- src/bin/cog_commit.rs
- src/conventional/commit.rs
- src/lib.rs
- src/settings/mod.rs
- tests/cog_tests/mod.rs
- tests/cog_tests/verify.rs
- tests/helpers.rs
- tests/lib_tests/cocogitto.rs
closes https://github.com/cocogitto/cocogitto/issues/166
> feat(verify): add the ability to forbid merge commit via configuration

- src/hook/mod.rs
I still need to do a bit of testing manually but this can be reviewed already
closes #209
> fix(hook): correctly escape hook commands by removing shell-word usage

- src/git/revspec.rs
When checking all the commits, `cog check` should not exit
if parent is not found because this is perfectly normal
when working in a shallow repository.
This patch modifies this behavior so the `all_commits` method
simply returns less commits (all the commits availables in the
shallow repository).
> fix: do not exit on parent not found (all_commits)

- Cargo.lock
- Cargo.toml
- docs/Packaging.md
- src/bin/cog/main.rs
As this feature might be a bit hard to discover, I also added  some documentation in `docs/Packaging.md`.
Discussion welcome! 😄
> feat(cli): add subcommand for generating manpages

- src/bin/cog/commit.rs
- src/bin/cog/main.rs
- src/command/bump/mod.rs
- src/command/bump/monorepo.rs
- src/command/bump/package.rs
- src/command/bump/standard.rs
- src/command/changelog.rs
- src/command/get_version.rs
- src/command/log.rs
- src/command/mod.rs
- src/conventional/bump.rs
- src/conventional/changelog/error.rs
- src/conventional/error.rs
- src/error.rs
- src/git/error.rs
- src/git/oid.rs
- src/git/revspec.rs
- src/git/stash.rs
- src/git/tag.rs
- src/log/output.rs
- tests/cog_tests/get_version.rs
- tests/cog_tests/mod.rs
Added the read-only feature "get-version", that will output the latest version, if any.
Closes #222
> feat(cli): Added get-version feature

- src/command/bump/mod.rs
- src/command/bump/monorepo.rs
- src/command/bump/package.rs
- src/command/bump/standard.rs
- src/conventional/bump.rs
- src/conventional/version.rs
- tests/lib_tests/bump.rs
Related issue : https://github.com/cocogitto/cocogitto/issues/270
> fix(bump): bump don't throw error on no bump types commits

- README.md
- cog.toml
These two links would previously 404.
> docs(README): fix links to cocogitto docs

- src/command/bump/monorepo.rs
- src/command/bump/package.rs
- src/command/bump/standard.rs
- src/command/commit.rs
- src/command/init.rs
- src/git/commit.rs
- src/git/monorepo.rs
- src/git/repository.rs
- src/git/revspec.rs
- src/settings/mod.rs
- tests/cog_tests/bump.rs
- tests/cog_tests/changelog.rs
- tests/lib_tests/bump.rs
Passing locally.
Had to add a new allow here https://github.com/cocogitto/cocogitto/pull/319/files#diff-9e57936c883548f522247f66eb2d1dc466ac71ec81d9b81dfc587f06e956473dR156, not terribly happy about that but it felt like a much bigger refactor to pull out the arguments.
> feat: Allow users to disable changelog generation

- Cargo.lock
- Cargo.toml
- src/git/commit.rs
- tests/cog_tests/commit.rs
- tests/helpers.rs
> chore: update dependencies

- .github/workflows/Deploy.yaml
Close https://github.com/cocogitto/cocogitto/issues/346
> ci: fix the format of release assets

- docs/website/config/README.md
- src/git/revspec.rs
- src/settings/mod.rs
> feat: add additional package path filtering options

- src/command/bump/mod.rs
Use commit metadata configuration to get a list of non bump commits as using conventional commit type fix and feat does not take into account the dynamic configuration. This way only commits with bump_patch, bump_minor and breaking change get excluded from the list.
> fix(bump): use commit meta to determine no bump commits

- .github/workflows/Deploy.yaml
- README.md
Resolves https://github.com/cocogitto/cocogitto/issues/369
> ci: fixed copy wrong path

- src/bin/cog/main.rs
- src/command/commit.rs
- src/git/repository.rs
- tests/cog_tests/commit.rs
Resolves https://github.com/cocogitto/cocogitto/issues/354
> Add files option for cog commit

- src/git/commit.rs
- src/git/error.rs
- src/git/repository.rs
Due to gitsign relying on oauth 2 browser redirection this feature has no automated test
Closes #226
> feat(commit): add gitsign support

- docs/website/ci_cd/README.md
- docs/website/config/README.md
- docs/website/guide/README.md
- docs/website/index.md
- docs/website/template/README.md
Hey, really enjoying the project.
I noticed a few typos in the docs, so I went ahead and fixed them.
> docs(website): fix some typos

- src/conventional/changelog/release.rs
- tests/cog_tests/changelog.rs
> fix: fix ignore merge commit no longer honored

- src/command/bump/monorepo.rs
- src/settings/mod.rs
- tests/cog_tests/changelog.rs
- tests/lib_tests/bump.rs
- website/reference/config.md
> feat: allow to disable package tagging for monorepos

- README.md
- website/index.md
- Fix some of the broken links in project README that point to the website docs
- Fix the link for "Getting Started" button on website docs
> fix: fixed broken link in project readme and docs

- Cargo.lock
- Cargo.toml
bump git2 crate to use libgit2 1.9
> chore(deps): update git2 to 0.20.0

- src/conventional/commit.rs
- src/git/commit.rs
- src/git/status.rs
- src/git/tag.rs
> fix: fix ssh signing
